travis:
  secure:
    BINSTAR_TOKEN: fA4pi3KpoCgeoI89tu/ftjRm8kPwBsZYTFSn2bz3Ow/0w78IEf3TEry5jem6MWRjG8NHYtUZJ2vwRg8nGHRx83+Nss96HHW6CbkpE0qCEiJt4TtqtPc/a0ilUpPdnV2rgC3WJdnFAW+Op2j2Pi8rqajZzUjMeAMx4wxmgtqpaL1qYDqmt3Fzln9FOODR5hHq8jD/nqosv42FFUmjCTW+ezGVZKDEBGbSrNsSoJchp4IZr+1FCa3zxfETNKSS2JRPPnLP2hDtKOAANoEpA7Tvkg1GnuZesEZIhZ82X73WK8a8kctZjSn7NdiczZ66635rv1pQTMASKrEdUs2CZ0YUaQimaDekhEUkUpF/+VIjCq2+4s946JvwLhUZd42Qfu6NFhhXoey1qCLCZ4vb7DCweYGHU7LkmrvOAprfisMJV03rCkFobA6pqrMlkKHoUQteTDwCyis7tjZ8PZit5cbfXLZ9CrWw7IS5V2uFABs1BwYe4piSfZfp8wE38pQYUGw97Sh2mGCSMWrh2mDXS1vKE5eHfxlAiwssXSvtWv2Cpv1bgVf/H6iqF3orSurjk1iN9R1JeudmVi3JoZMLxYxG7b9V5TtVCpJRt4Og9RaysMqbGqr8yzE1WtWv34irEOGV7D53BkgEMW47jgx7zUBznwSf5DTh7Nv648wH/x3PhnE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
